### PR TITLE
I altered some stuff

### PR DESCRIPTION
**Pull request by juliancoates**
I added aline and modified a line, check it and merge it please!

### CODE REVIEW

**Comment by Julianatwave** [comment]
I dunno is crap init.

**Comment by Julianatwave** [comment]
nah is well gd tho.

**Comment by juliancoates** [comment]
u jokin merge it

**Comment by Julianatwave** [comment]
ok wil merg

**Comment by Julianatwave** [comment]
merged it

**Comment by juliancoates** [comment]
ok will delete branch ting

**Pull request merged**
